# if you use SGE cluster, set the maximum number of jobs
#sge_jobs: 10

# path to Rscript
rscript_path: /usr/local/package/r/3.6.0/bin/Rscript

# mRNA expression levles in GCT format.
# The 1st column must be gene symbols.
# Multiple files can be listed.
expression:
  - example/LUAD_n10.gct

# gene sets for ssGSEA
gene_set:
  - data/h.all.v6.2.symbols.gmt
  - data/Bindea2013.gmt
  - data/Charoentong2017.gmt

# gene of interest. Their expression levels are included in the output.
goi: example/gene_of_interest.txt

# sample annotations
annotation: example/annotation.txt
