name: immunoduct
channels:
  - r
  - bioconda
dependencies:
  - snakemake
  - r-base
  - r-dplyr
  - r-tidyr
  - r-data.table
  - r-readr
  - bioconductor-gsva
  - r-rcurl
  - r-bit64
  - scikit-learn
  - r-e1071
  - bioconductor-preprocesscore
